### ISSUE TITLE
fortios_system_snmp_user query around multiple "notify-host" values

### ISSUE THREAD

**Issue by JonTheNiceGuy** [fortinet-solutions-cse/ansible_fgt_modules#12]
Hi, I'm working with this playbook:

```
- name: SNMP user configuration.
  fortios_system_snmp_user:
    host:  "192.0.2.1"
    username: admin
    password: ""
    vdom:  root
    https: true
    system_snmp_user:
      state: "present"
      name: public
      security-level: "auth-priv"
      auth-proto: sha
      auth-pwd: public
      priv-proto: aes256
      priv-pwd: public
      notify-hosts: "192.0.2.10 192.0.2.11"
      events: "cpu-high mem-low log-full intf-ip ips-signature ips-anomaly av-virus av-oversize av-pattern av-fragmented bgp-established bgp-backward-transition ent-conf-change av-conserve av-bypass av-oversize-passed av-oversize-blocked ips-pkg-update ips-fail-open load-balance-real-server-down per-cpu-high"
      ha-direct: enable
      status: enable
```

and here's the `diagnose debug application httpsd -9` output:

```
[httpsd 179 - 1556873270     info] ap_invoke_handler[593] -- new request (handler='api_cmdb_v2-handler', uri='/api/v2/cmdb/system.snmp/user?vdom=root', method='POST')
[httpsd 179 - 1556873270     info] ap_invoke_handler[597] -- User-Agent: python-requests/2.21.0
[httpsd 179 - 1556873270     info] ap_invoke_handler[600] -- Source: 10.0.2.2:53779 Destination: 10.0.2.15:443
[httpsd 179 - 1556873270     info] api_cmdb_v2_handler[2048] -- received api_cmdb_v2_request from '10.0.2.2'
[httpsd 179 - 1556873270     info] aps_init_process_vdom[1195] -- initialized process vdom to 'root' (cookie='(null)')
[httpsd 179 - 1556873270     info] api_store_parameter[227] -- add API parameter 'vdom': '"root"' (type=string)
[httpsd 179 - 1556873270     info] api_store_parameter[227] -- add API parameter 'status': '"enable"' (type=string)
[httpsd 179 - 1556873270     info] api_store_parameter[227] -- add API parameter 'notify-hosts': '"192.0.2.10 192.0.2.11"' (type=string)
[httpsd 179 - 1556873270     info] api_store_parameter[227] -- add API parameter 'priv-proto': '"aes256"' (type=string)
[httpsd 179 - 1556873270     info] api_store_parameter[227] -- add API parameter 'name': '"public"' (type=string)
[httpsd 179 - 1556873270     info] api_store_parameter[227] -- add API parameter 'auth-pwd': '********' (type=string)
[httpsd 179 - 1556873270     info] api_store_parameter[227] -- add API parameter 'trap-status': '"enable"' (type=string)
[httpsd 179 - 1556873270     info] api_store_parameter[227] -- add API parameter 'priv-pwd': '********' (type=string)
[httpsd 179 - 1556873270     info] api_store_parameter[227] -- add API parameter 'security-level': '"auth-priv"' (type=string)
[httpsd 179 - 1556873270     info] api_store_parameter[227] -- add API parameter 'events': '"cpu-high mem-low log-full intf-ip ips-signature ips-anomaly av-virus av-oversize av-pattern av-f                  ragmented bgp-established bgp-backward-transition ent-conf-change av-conserve av-bypass av-oversize-passed av-oversize-blocked ips-pkg-update ips-fail-open load-balance-real-server-down per                  -cpu-high"' (type=string)
[httpsd 179 - 1556873270     info] api_store_parameter[227] -- add API parameter 'queries': '"enable"' (type=string)
[httpsd 179 - 1556873270     info] api_store_parameter[227] -- add API parameter 'ha-direct': '"enable"' (type=string)
[httpsd 179 - 1556873270     info] api_store_parameter[227] -- add API parameter 'auth-proto': '"sha"' (type=string)
[httpsd 179 - 1556873270     info] handle_cli_req_v2_vdom[1950] -- new CMDB API request (vdom='root',user='admin')
[httpsd 179 - 1556873270     info] api_cmdb_request_init_by_path[1351] -- new CMDB query (path='system.snmp',name='user')
[httpsd 179 - 1556873270    error] log_error_core[439] -- [Fri May  3 08:47:50 2019] [error] [client 10.0.2.2] [libapreq] unknown content-type: `(null)'
[httpsd 179 - 1556873270     info] api_return_cmdb_revision[779] -- ETag check for system.snmp.user
[httpsd 179 - 1556873270     info] _api_cmdb_v2_config[1136] -- editing CLI object (append=1, auto_key=0, path=system.snmp, name=user, mkey=(null), flags=0)
[httpsd 179 - 1556873270     info] api_set_cmdb_attr[1677] -- 'name': 'public'
[httpsd 179 - 1556873270     info] api_set_cmdb_attr[1677] -- 'status': 'enable'
[httpsd 179 - 1556873270     info] api_set_cmdb_attr[1677] -- 'trap-status': 'enable'
[httpsd 179 - 1556873270     info] api_set_cmdb_attr[1677] -- 'queries': 'enable'
[httpsd 179 - 1556873270    error] api_set_cmdb_attr[1673] -- set_value_to_cmdb failed for node 'notify-hosts': '192.0.2.10 192.0.2.11' (err=-8)
[httpsd 179 - 1556873270    error] cmdb_commit_from_json[1465] -- error converting request to CLI object (-8)
[httpsd 179 - 1556873270    error] _api_cmdb_v2_config[1163] -- error editing object (nret=-8)
[httpsd 179 - 1556873270    error] api_return_http_result[631] -- API error -8 raised
[httpsd 179 - 1556873270     info] ap_invoke_handler[616] -- request completed (handler='api_cmdb_v2-handler' result==0)
```

It looks like it's failing on the notify-hosts line (validated - reduce the hosts to just `192.0.2.10` and it works). How can I define multiple hosts?
