### ISSUE TITLE
Issue with logging in when the password contains an "&" symbol

### ISSUE THREAD

**Issue by JonTheNiceGuy** [fortinet-solutions-cse/ansible_fgt_modules#13]
If you create a username: `failadmin` and a password: `decaf&BAD123` and then perform a sample action:

```
- fortios_firewall_address:
    host: "192.0.2.1"
    username: "failadmin"
    password: "decaf&BAD123"
    vdom: "root"
    https: "true"
    firewall_address:
      state: "absent"
      name: "somerandomentry"
```

This will fail showing "login failed". Change the password to `decafBAD123` on both FW and in the playbook and it works. This also occurs in the [fortiosconfig module](https://github.com/fortinet-solutions-cse/40ansible).
