### ISSUE TITLE
fortios_system_admin: ssh_public_key1 not properly set (split on whitespace)

### ISSUE THREAD

**Issue by sbraz** [fortinet-solutions-cse/ansible_fgt_modules#23]
Hi,
With ansible 2.9.2, if I run the following task on a Fortigate 60D (`v6.0.6,build0272,190716`):
```
    fortios_system_admin:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "True"
      ssl_verify: "False"
      state: "present"
      system_admin:
        name: "testuser"
        accprofile: "super_admin"
        ssh_public_key1: "ssh-rsa blahblah"
```

I end up with the following on the firewall:
```
set ssh-public-key1 "blahblah"
```
If the user doesn't exist (and I add a `password` parameter), it's even worse: the module fails with `Error in repo`. The debug shows that the key parameters are split on whitespace:
```
[httpsd 119 - 1576144799     info] api_store_parameter[227] -- add API parameter 'ssh-public-key1': '"ssh-rsa blahblah"' (type=string)  
[httpsd 119 - 1576144799    error] api_set_cmdb_attr[1638] -- cmd_check_value failed for node 'ssh-public-key1': 'ssh-rsa' (err=-651)
[httpsd 119 - 1576144799    error] api_set_cmdb_attr[1638] -- cmd_check_value failed for node 'ssh-public-key1': 'blahblah' (err=-651)
```

Changing the parameter to double-quote it like this makes it work:
```
ssh_public_key1: "'ssh-rsa blahblah'"
```
The debug output shows:
```
[httpsd 130 - 1576145007     info] api_store_parameter[227] -- add API parameter 'ssh-public-key1': '"'ssh-rsa blahblah'"' (type=string)                                                                                           
[httpsd 130 - 1576145007     info] api_set_cmdb_attr[1677] -- 'ssh-public-key1': 'ssh-rsa blahblah'
```

Seeing how the problem is not present with `trusthost1` which also contains spaces, I assume that this is a FortiOS API bug?
