### ISSUE TITLE
fortios_system_interface: vdom parameter can be set at system_interface or system_interface level

### ISSUE THREAD

**Issue by sbraz** [fortinet-solutions-cse/ansible_fgt_modules#25]
Hi,
Whereas most modules use the top-level `vdom` parameter, this module only seems to use the parameter under `system_interface`.

This task works:
```yaml
fortios_system_interface:
  host:  "{{ host }}"
  username: "{{ username }}"
  password: "{{ password }}"
  https: "True"
  ssl_verify: "False"
  state: "present"
  system_interface:
    name: "loopback"
    vdom:  "{{ vdom }}"
    type: "loopback"
    role: "undefined"
    ip: "169.254.0.1/32"
    allowaccess:
      - https
      - ping
      - ssh
      - snmp
    status: "up"
```

But this one (with vdom set at the top-level) doesn't:
```yaml
fortios_system_interface:
  host:  "{{ host }}"
  username: "{{ username }}"
  password: "{{ password }}"
  vdom:  "{{ vdom }}"
  https: "True"
  ssl_verify: "False"
  state: "present"
  system_interface:
    name: "loopback"
    type: "loopback"
    role: "undefined"
    ip: "169.254.0.1/32"
    allowaccess:
      - https
      - ping
      - ssh
      - snmp
    status: "up"
```

In that second case, the `vdom` parameter isn't passed and the API refuses to create the interface.

This means that:
* `vdom` should be required
*  if possible, the top-level `vdom` parameter should be used and the other one should be removed
