### ISSUE TITLE
fortios vpn ipsec phase1 interface issue

### ISSUE THREAD

**Issue by shariaty59** [fortinet-solutions-cse/ansible_fgt_modules#28]
@mamunozgonzalez Hi,
I am trying to confing a VPN on a fortigate using ansible. Since I figured the only required fields are "name" and "state", I tried to keep it as simple as possible: 

```
---
- hosts: localhost
  vars:
    host: "192.168.1.1"
    username: "admin"
    password: "admin"
    vdom: "root"
    ssl_verify: "False"

  tasks:
  - name: Configure Phase1 Interface
    fortios_vpn_ipsec_phase1_interface:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "True"
      vpn_ipsec_phase1_interface:
        state: "present"
        name: "TEST-VPN"
```
When I run the playbook, I get this error:
```
TASK [Configure Phase1 Interface] **********************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "meta": {"build": 272, "error": -651, "http_method": "POST", "http_status": 500, "name": "phase1-interface", "path": "vpn.ipsec", "revision": "55.0.0.9549055138899054456.1568913641", "serial": "FGVM080000069462", "status": "error", "vdom": "root", "version": "v6.0.6"}, "msg": "Error in repo"}
```

I ran some debugs at the same time of running the playbook and this is what I get:
```
TEST-FW # diagnose debug enable
TEST-FW # diagnose debug cli 8
Debug messages will be on for 30 minutes.

TEST-FW # 0: config vpn ipsec phase1-interface

0: config vpn ipsec phase1-interface
0: edit "TEST-VPN"
0: set peertype any
0: set proposal aes128-sha256 aes256-sha256 aes128-sha1 aes256-sha1
-651: end
```
Please advise.
Best regards,

**Comment by chillancezen** [comment]
hi,

only name and state are not enough to create a phase1-ineterface instance:
please consider a minimum config collection of fields:
```
- hosts: localhost
  vars:
   host: <your fgt device address>
   username: "admin"
   password: "ca$hc0w"
   vdom: "root"
   ssl_verify: "False"
  tasks:
  - name: Configure VPN remote gateway.
    fortios_vpn_ipsec_phase1_interface:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "True"
      state: "present"
      ssl_verify: "False"
      vpn_ipsec_phase1_interface:
        interface: 'port1'
        name: 'Foo'
        net_device: 'disable'
        proposal:  'des-md5'
```

thanks,
Link

**Comment by shariaty59** [comment]
@chillancezen Thank you for the response. so at first try I added ssl_verify: "False" to "fortios_vpn_ipsec_phase1_interface" and it seems like it did not like it so I deleted it. 

`fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (fortios_vpn_ipsec_phase1_interface) module: ssl_verify Supported parameters include: host, https, password, username, vdom, vpn_ipsec_phase1_interface"}`

as far as net_device: 'disable', it seems like it is not a valid option:

```
TASK [Configure Phase1 Interface] ******************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (fortios_vpn_ipsec_phase1_interface) module: net_device found in vpn_ipsec_phase1_interface. Supported parameters include: acct-verify, add-gw-route, add-route, assign-ip, assign-ip-from, authmethod, ...
```

any advice?
Thank you.

**Comment by chillancezen** [comment]
for ansible 2.9.0, the following script works fine to create a new phase1 interface.
```
- hosts: localhost
  vars:
   host: 172.22.13.10
   username: "admin"
   password: "ca$hc0w"
   vdom: "root"
   ssl_verify: "False"
  tasks:
  - name: Configure VPN remote gateway.
    fortios_vpn_ipsec_phase1_interface:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "True"
      state: "present"
      ssl_verify: "False"
      vpn_ipsec_phase1_interface:
        interface: 'port1'
        name: 'foo_phase1_interface_0'
        net_device: 'disable'
        proposal:  'des-md5'
        peertype: 'any'
        wizard_type: 'static-fortigate'
        remote_gw: '22.33.44.56'
        psksecret: 'foo-password'
```


for ansible 2.8.0, there is no way to escape invalid ssl validation, don't use ansible 2.8

to upgrade to 2.9.0.
please run 
```
#pip3 install ansible==2.9.0
```

thanks.
Link
