### ISSUE TITLE
Initial test of modules

### ISSUE THREAD

**Issue by haodeon** [fortinet-solutions-cse/ansible_fgt_modules#3]
After getting around my initial problem with fortiosapi and passwords. I managed to do some testing of these modules against a 6.0.3 appliance.

I am by no means an ansible expert, nor am I a fortigate expert. I'm learning both technologies at the same time. At the moment I am going through the guides on the fortinet cookbook site and then translating them into ansible plays. In between I destroy and recreate my environment via Terraform. I verify ansible does what I expect by looking at the CLI configuration through the show command.

I am happy to say my very simple playbook below works without any issues.

```
---
- hosts: localhost
  vars:
   host: "x.x.x.x"
   username: "admin"
   password: ""
   vdom: "root"
  gather_facts: no
  tasks:
  - name: Configure global attributes.
    fortios_system_global:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "true"
      system_global:
        timezone: "nn"
  - name: Configure port2 interface.
    fortios_system_interface:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "true"
      system_interface:
        state: "present"
        name: "port2"
        mode: "dhcp"
        allowaccess: "ssh"
  - name: Configure HA.
    fortios_system_ha:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "true"
      system_ha:
        session-pickup: "enable"
        session-pickup-connectionless: "enable"
        session-pickup-expectation: "enable"
        session-pickup-nat: "enable"
        override: "disable"
  - name: Configure FortiGate Session Life Support Protocol (FGSP) session synchronization.
    fortios_system_cluster_sync:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "true"
      system_cluster_sync:
        state: "present"
        sync-id: "1"
        peerip: "10.x.x.x"
        syncvd:
         - name: "root"
```

At the moment, I am concentrating on just configuring one firewall. In my environment though there are two firewalls synced via FGSP. What would be the best way to configure both firewalls at the same time using ansible? I would like the playbook to run so that each task is duplicated across both firewalls simultaneously, that way I can be sure the configuration on both are matching at each step.
