### ISSUE TITLE
Nested Loop for Phase 2 selectors

### ISSUE THREAD

**Issue by shariaty59** [fortinet-solutions-cse/ansible_fgt_modules#33]
Hi, Please accept y apology if my question might be very ansible basic and not directly related to fortios. on all our phase 2 selectors, we do a one to one mapping between all IPs. so I was looking for a way to nested loop the source and the destination subnets. I am passing a configuration file as below:

```
---
remote_subnets:
   - network: 10.20.30.0
     subnet: 255.255.255.0
   - network: 10.20.40.100
     subnet: 255.255.255.255

local_subnets:
   - network: 150.20.30.32
     subnet: 255.255.255.255
   - network: 150.20.40.0
     subnet: 255.255.255.0
```

and on the playbook trying to use both list on a single loop, which obviously didn't work.

```
---
  - name: Configure Phase2 Interface
    fortios_vpn_ipsec_phase2_interface:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "True"
      state: "present"
      ssl_verify: "False"
      vpn_ipsec_phase2_interface:
        name: 'UX_and_Ansible'
        phase1name: 'ANSIBLE_VPN_TEST'
        proposal: 'des-sha512'
        dhgrp: '2'
        auto_negotiate: 'enable'
        keylife_type: 'seconds'
        keylifeseconds: '28800'
        dst_addr_type: 'subnet'
        src_addr_type: 'subnet'
        src_subnet: "{{ remote_subnets.network }} {{ remote_subnets.subnet }}"
        dst_subnet: "{{ local_subnets.network }} {{ local_subnets.subnet }}"
      loop:
       - "{{ remote_subnets }}"
       - "{{ local_subnets }}"
```

I appreciate you help me fix this syntax.
Regards,

**Comment by chillancezen** [comment]
`ETA: 3/15 2020`

**Comment by chillancezen** [comment]
@shariaty59 ,

sorry for late update. 

please consider this: define an array and use `with_items` keyword.
```

  networks:
   - {remote_network: 10.20.30.0, remote_subnet: 255.255.255.0, local_network: 150.20.30.32, local_subnet: 255.255.255.255}
   - {remote_network: 10.20.40.100, remote_subnet: 255.255.255.255, local_network: 150.20.40.0, local_subnet: 255.255.255.0}




  - name: Configure Phase2 Interface
    fortios_vpn_ipsec_phase2_interface:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "True"
      state: "present"
      ssl_verify: "False"
      vpn_ipsec_phase2_interface:
        name: 'UX_and_Ansible'
        phase1name: 'ANSIBLE_VPN_TEST'
        proposal: 'des-sha512'
        dhgrp: '2'
        auto_negotiate: 'enable'
        keylife_type: 'seconds'
        keylifeseconds: '28800'
        dst_addr_type: 'subnet'
        src_addr_type: 'subnet'
        src_subnet: "{{ item.remote_network }} {{ item.remote_subnet }}"
        dst_subnet: "{{ item.local_network }} {{ item.local_subnet }}"
      with_items:
     	- "{{ networks }}"
```


thanks,
Link
