### ISSUE TITLE
Getting 405 error in repo error for fortios_system_ntp module 

### ISSUE THREAD

**Issue by venudevannagari** [fortinet-solutions-cse/ansible_fgt_modules#34]
I have tried "fortios_system_ntp module" to configure ntp on fortigate in Ansible 2.9.3.My fortigate version is 6.2.3.Python version is 2.7.

I have got the following error.

 [localhost]: FAILED! => {\n\n \"changed\": false, \n\n \"invocation\": {\n\n \"module_args\": {\n\n \"host\": \"172.22.105.17\", \n\n \"https\": false, \n\n \"password\": \"VALUE_SPECIFIED_IN_NO_LOG_PARAMETER\", \n\n \"ssl_verify\": false, \n\n \"system_ntp\": {\n\n \"interface\": null, \n\n \"ntpserver\": [\n\n {\n\n \"id\": \"5\", \n\n \"server\": \"80.214.34.56\"\n\n }\n\n ], \n\n \"ntpsync\": \"enable\", \n\n \"server_mode\": \"enable\", \n\n \"source_ip\": \"172.22.105.17\", \n\n \"source_ip6\": null, \n\n \"syncinterval\": 10, \n\n \"type\": \"custom\"\n\n }, \n\n \"username\": \"admin\", \n\n \"vdom\": \"root\"\n\n }\n\n }, \n\n \"meta\": {\n\n \"build\": 1066, \n\n \"http_method\": \"POST\", \n\n \"http_status\": 405, \n\n \"name\": \"ntp\", \n\n \"path\": \"system\", \n\n \"serial\": \"FGVMEV0000000000\", \n\n \"status\": \"error\", \n\n \"vdom\": \"root\", \n\n \"version\": \"v6.2.3\"\n\n }, \n\n \"msg\": \"Error in repo\"\n\n}\n\n\n\nPLAY RECAP *********************************************************************\n\nlocalhost : ok=0 changed=0 unreachable=0 failed=1 skipped=0 rescued=0 ignored=0 \n\n\n\n\n\n below is the cmd, we are executing on ansible server ::\n ansible-playbook /etc/ansible/playbook/Network-Security/Networks.yml --extra-vars \"forti_ip=172.22.105.17 vdom=root ntp_key_id=5 ntp_server=80.214.34.56 ntp_server_sync=enable ntp_server_mode=enable source_ip=172.22.105.17 ntp_sync_interval=10 ntp_server_type=custom\" --tags \"fortigate_configureNTP_creation\" -vvvv"}

Can you guys please resolve this issue.

**Comment by chillancezen** [comment]
`ETA: 3/15 2020`

**Comment by chillancezen** [comment]
hi @venudevannagari, 

you must set `interface` in your playbook like this:
```
#cat test.yml
- hosts: fortigates
  collections:
  - fortinet.fortios
  connection: httpapi
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 443
   firewall_address_group: "firewall_addrgrp_obj0"
  tasks:
  - name: Configure System NTP
    fortios_system_ntp:
      vdom:  "{{ vdom }}"
      https: True
      system_ntp:
        interface:
            - interface_name: 'port1'
        ntpserver:
            - id: 5
              server: '80.214.34.56'
        ntpsync: enable
        server_mode: enable
        source_ip: '192.168.190.137'
        syncinterval: 10
        type: custom
```

I reproduced the playbook with pure CLI script, it reports errors like this:
```
FGVM04TM19006963 (ntp) # show
path=system, objname=ntp, tablename=(null), size=48
config system ntp
    set ntpsync enable
    set type custom
    set syncinterval 10
    config ntpserver
        edit 5
            set server "80.214.34.56"
        next
    end
    set source-ip 192.168.190.137
    set server-mode enable
end

FGVM04TM19006963 (ntp) # end
cmd_clean_context 0, abort=0
There aren't any interfaces with NTP server enabled.
object set operator error, -651 discard the setting
Command fail. Return code -651
```

It's sad that debug info can not display the specific error info.

thanks,
Link
