### ISSUE TITLE
Multiple issues with fortios_system_admin module

### ISSUE THREAD

**Issue by JonTheNiceGuy** [fortinet-solutions-cse/ansible_fgt_modules#4]
I'm working on some automation with @tohillm and with the following playbook:

```yaml
---
- hosts: localhost
  gather_facts: false
  vars:
      host1: "192.0.2.1"
      fw_username: "admin_user"
      fw_password: "20190115_Admin"
      user_username: "radius_user"
      user_password: "20190115_User"
      vdom: "root"

  tasks:
  - name: Configure RADIUS server entries.
    fortios_user_radius:
      host:  "{{ host1 }}"
      username: "{{ fw_username }}"
      password: "{{ fw_password }}"
      https: True
      vdom: "{{ vdom }}"
      user_radius:
        state: "present"
        name: "radserv"
        radius-port: "1812"
        secret: "public"
        server: "192.0.2.2"
        source-ip: "192.0.2.1"
        timeout: "45"
        auth-type: "auto"

  - name: Configure auth group
    fortios_user_group:
      host:  "{{ host1 }}"
      username: "{{ fw_username }}"
      password: "{{ fw_password }}"
      https: True
      vdom: "{{ vdom }}"
      user_group:
        state: present
        group-type: firewall
        name: admin-radius
        member:   
        - name: NPS4

  - name: Configure admin users.
    fortios_system_admin:
      host:  "{{ host1 }}"
      username: "{{ fw_username }}"
      password: "{{ fw_password }}"
      https: True
      vdom: "{{ vdom }}"
      system_admin:
        state: "present"
        accprofile: "super_admin"
        name: "{{ user_username }}"
        password: "{{ user_password }}"
        vdom:
        - name: "{{ vdom }}"
        remote-auth: "enable"
        remote-group: "admin-radius"
        wildcard: enable
```

When I run this playbook, and I've copied `fortios_user_radius.py`, `fortios_user_group.py` and `fortios_system_admin.py` into `library/`, I get:

```
PLAY [localhost] **************************************************************************************************************************************************************************************************

TASK [Configure RADIUS server entries.] ***************************************************************************************************************************************************************************
changed: [localhost]

TASK [Configure auth group] ***************************************************************************************************************************************************************************************
changed: [localhost]

TASK [Configure admin users.] *************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "implementation error: unknown type password-2 requested for password"}

PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=2    unreachable=0    failed=1
```

If I edit `library/fortios_system_admin.py` and update (line 884)[https://github.com/fortinet-solutions-cse/ansible_fgt_modules/blob/c739655aed2bb1de27065b4ba3bc2c8c6de82f06/v6.0.2/system/fortios_system_admin.py#L844] to show:

```
"password": {"required": False, "type": "str"},
```

I then get the following:

```
PLAY [localhost] **************************************************************************************************************************************************************************************************

TASK [Configure RADIUS server entries.] ***************************************************************************************************************************************************************************
changed: [localhost]

TASK [Configure auth group] ***************************************************************************************************************************************************************************************
changed: [localhost]

TASK [Configure admin users.] *************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "meta": {"build": 200, "http_method": "PUT", "http_status": 403, "mkey": "radius_user", "name": "admin", "path": "system", "revision": "194.0.0.9544640475189144756.1547457824", "serial": "FGVM04TMxxxxxxx", "status": "error", "vdom": "root", "version": "v6.0.3"}, "msg": "Error in repo"}

PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=2    unreachable=0    failed=1   
```

It does complete successfully if I remove these lines from the last task:

```
        vdom:
        - name: "{{ vdom }}"
        remote-auth: "enable"
        remote-group: "admin-radius"
        wildcard: enable
```

I see two issues here:

1. `password` is defined as `password-2` which is not a known type - is this something internal that you need to share? 😄 Or, perhaps, this needs to be changed to `str`?
2. For some reason, one of these lines in the last block above prevents the user from being added. Please can you advise?
