### ISSUE TITLE
Request for improvement: some call around "execute vpn certificate local generate"

### ISSUE THREAD

**Issue by JonTheNiceGuy** [fortinet-solutions-cse/ansible_fgt_modules#5]
Here's our current workflow:

1) SSH in
2) Execute `execute vpn certificate local generate rsa certname 4096 192.0.2.1 CN Country State City OU email@example.com`
3) HTTPS to 192.0.2.1, navigate to `system` -> `certificate` -> select certificate name -> `download` -> SaveAs cert.csr

Ideal workflow (psudocode):
```
---
- hosts: localhost
  tasks:
  - fortios_vpn_certificate_local_generate:
      type: rsa
      certname: abc123
      size: 4096
      dn: 192.0.2.1
      cn: CN
      country: Country
      state: State
      city: City
      ou: OU
      email: email@example.com
    register: cert
  - file:
      path: cert.csr
      content: "{{ cert }}"
```
