### ISSUE TITLE
Issue with fortios_firewall_addrgrp

### ISSUE THREAD

**Issue by JonTheNiceGuy** [fortinet-solutions-cse/ansible_fgt_modules#6]
I have the commit 6a7973c89ad2824532bd4b19601e4f0f21624761 (current head) of ansible_fgt_modules in library of my ansible repo, and I’ve got this playbook:

```
---
- hosts: localhost
  gather_facts: false
  tasks:
  - fortios_firewall_addrgrp:
      host: "192.0.2.1"
      username: breakglass
      password: mypassword
      vdom: root
      https: True
      firewall_addrgrp:
        state: present
        name: all_the_things
        member:
        - source_group_a
```

Assuming “`source_host_a`” exists as an address object, I *believe* this should create a group “`source_group_a`” with one member - “`source_host_a`”.

Instead, I get:

```
PLAY [localhost] *******************************************************************************************************************************************************************************

TASK [fortios_firewall_addrgrp] ****************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "meta": {"build": 200, "error": -1, "http_method": "POST", "http_status": 500, "name": "addrgrp", "path": "firewall", "revision": "5.0.76.9550766792421668275.1551864364", "serial": "FGVM08TMREDACTED", "status": "error", "vdom": "root", "version": "v6.0.3"}, "msg": "Error in repo"}

PLAY RECAP *************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1
```

I have previously created the address object using the api and the same credentials… so I know that works.

Is there anything I can check on the firewall to see why it’s returning a “500”? “diagnose debug enable / diagnose debug cli 8” isn’t showing me anything for this item.

**Comment by mamunozgonzalez** [comment]
Hi @JonTheNiceGuy ,
 this case is similar to what is described in https://github.com/fortinet-solutions-cse/ansible_fgt_modules/issues/7.

I'm showing a working example:
```
- hosts: localhost
  vars:
   host: "192.168.122.40"
   username: "admin"
   password: ""
   vdom: "root"
  tasks:
  - name: Configure IPv4 address groups.
    fortios_firewall_addrgrp:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "False"
      firewall_addrgrp:
        state: "present"
        allow-routing: "enable"
        color: "4"
        comment: "Comment."
        member:
         - name: "all"
         - name: "google-play"
        name: "source_group_a"
        visibility: "enable"
```

The difference is in the way 'member' is used. We have to add 'name' before the address. This example is creating an address group named "source_group_a" with addresses "all" and "google-play" ('all' already covers everything but it is just there to show multiple entries are possible).

Note that this module is already approved to be in Ansible 2.8 and you can see the official documentation with a better look:
https://docs.ansible.com/ansible/devel/modules/fortios_firewall_addrgrp_module.html#fortios-firewall-addrgrp-module

Another hint: It is useful to run some debug commands to check why FortiGate is complaining about ansible/http api operations. Just type in the CLI:

diagnose debug application httpsd -1
diagnose debug enable

And the traces will give you some useful hints.

Hope that helps
