### ISSUE TITLE
Issue with fortios_firewall_policy

### ISSUE THREAD

**Issue by JonTheNiceGuy** [fortinet-solutions-cse/ansible_fgt_modules#7]
I have the commit 6a7973c89ad2824532bd4b19601e4f0f21624761 (current head) of ansible_fgt_modules in library of my ansible repo, and I’ve got this playbook:

```
---
- hosts: localhost
  gather_facts: false
  tasks:
  - fortios_firewall_policy:
      host: "192.0.2.1"
      username: breakglass
      password: mypassword
      vdom: root
      https: True
      firewall_policy:
        state: "present"
        policyid: "2002"
        name: "Policy_2002"
        action: "deny"
        srcintf: "any"
        dstintf: "any"
        srcaddr: ['all']
        dstaddr: ['all']
        service: ['HTTP','HTTPS']
        schedule: "always"
        nat: "disable"
        logtraffic: "all"
        logtraffic-start: "disable"
        uuid: "20190306-2321-0001-2002-e5167ed833c7"
```
And here’s my output:

```
PLAY [localhost] *******************************************************************************************************************************************************************************

TASK [fortios_firewall_policy] *****************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "meta": {"build": 200, "error": -651, "http_method": "POST", "http_status": 500, "name": "policy", "path": "firewall", "revision": "984.0.0.95
50766792421668275.1551864364", "serial": "FGVM08TMREDACTED", "status": "error", "vdom": "root", "version": "v6.0.3"}, "msg": "Error in repo"}

PLAY RECAP *************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1
```

Interestingly, the `diagnose debug cli 8` on this shows the following:

```
0: config firewall policy
--
0: edit 2002
0: set name "Policy_2002"
-651: set srcintf ""
(skipped) set dstintf ""
(skipped) set srcaddr ""
(skipped) set dstaddr ""
(skipped) set schedule "always"
(skipped) set service "" ""
(skipped) set logtraffic all
(skipped) unset groups
(skipped) unset users
(skipped) unset devices
(skipped) unset custom-log-fields
(skipped) unset ssl-mirror-intf
```

**Comment by mamunozgonzalez** [comment]
Hi @JonTheNiceGuy,
  I have modified your example to make it compatible with the format that ansible expects. I guess the confusion comes from 40ansible/fortiosconfig module which is also able to do these operations but follows a slightly different approach. In this case we have to do it as follows:

```
- hosts: localhost
  gather_facts: false
  tasks:
  - fortios_firewall_policy:
      host: "192.168.122.40"
      username: admin
      password: ""
      vdom: root
      https: False
      firewall_policy:
        state: "present"
        policyid: "2002"
        name: "Policy_2002"
        action: "deny"
        srcintf:
          - name: any
        dstintf:
          - name: any
        srcaddr: 
          - name: 'all'
        dstaddr:
          - name: 'all'
        service: 
          - name: 'HTTP'
          - name: 'HTTPS'
        schedule: "always"
        nat: "disable"
        logtraffic: "all"
        logtraffic-start: "disable"
        uuid: "20190306-2321-0001-2002-e5167ed833c7"

```
The main difference is in the way the lists are handled. The example included in the module itself (.py file) can also give you an idea. 
Note that this module is already approved to be in Ansible 2.8 and you can see the official documentation with a better look: 
https://docs.ansible.com/ansible/devel/modules/fortios_firewall_policy_module.html#fortios-firewall-policy-module

Another hint: It is useful to run some debug commands to check why FortiGate is complaining about ansible/http api operations. Just type in the CLI:

```
diagnose debug application httpsd -1
diagnose debug enable
```
And the traces will give you some useful hints.

Hope that helps
