### ISSUE TITLE
Issue with fortios_system_ntp 

### ISSUE THREAD

**Issue by JonTheNiceGuy** [fortinet-solutions-cse/ansible_fgt_modules#9]
Using this playbook:

```yml
---
- hosts: localhost
  gather_facts: false
  tasks:
  - fortios_system_ntp:
      host: "10.10.10.4"
      username: myuser
      password: mypassword
      vdom: root
      https: True
      system_ntp:
        interface:
        - port1
        ntpserver:
        - id: 1
          server: "192.0.2.1"
        - id: 2
          server: "192.0.2.2"
        ntpsync: enable
        server-mode: disable
        source-ip: "0.0.0.0"
        syncinterval: 3
        type: custom
```

I'm getting [this response](https://gist.github.com/JonTheNiceGuy/d0bba7b21e274f6777773bcf1e6f442e#file-output-log):
```
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "host": "10.10.10.4",
            "https": true,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "system_ntp": {
                "interface": [
                    "port1"
                ],
                "ntpserver": [
                    {
                        "id": 1,
                        "server": "192.0.2.1"
                    },
                    {
                        "id": 2,
                        "server": "192.0.2.2"
                    }
                ],
                "ntpsync": "enable",
                "server-mode": "disable",
                "source-ip": "0.0.0.0",
                "syncinterval": 3,
                "type": "custom"
            },
            "username": "myuser",
            "vdom": "root"
        }
    },
    "meta": {
        "build": 200,
        "http_method": "POST",
        "http_status": 405,
        "name": "ntp",
        "path": "system",
        "serial": "FGVM08TMREDACTED",
        "status": "error",
        "vdom": "root",
        "version": "v6.0.3"
    },
    "msg": "Error in repo"
}
```

In [this gist](https://gist.github.com/JonTheNiceGuy/d0bba7b21e274f6777773bcf1e6f442e) there is also [HTTP flows (from MITMproxy)](https://gist.github.com/JonTheNiceGuy/d0bba7b21e274f6777773bcf1e6f442e#file-http_log-txt) and [`diagnose debug application httpsd -1` logs](https://gist.github.com/JonTheNiceGuy/d0bba7b21e274f6777773bcf1e6f442e#file-debug-log)
